# Generated by Django 2.1.15 on 2020-06-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='timeline_audio/'),
        ),
    ]
